packages:
  - "."

allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  bcrypt: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - "@nestjs/core"
  - unrs-resolver
  - bcrypt
  - "@scarf/scarf"
  - esbuild
  - msgpackr-extract
