//error-docs.ts dùng cho Swagger error description.
export const ERROR_HINTS: Record<string, string> = {
  'Error.AccountBanned': 'account is banned or blocked',
  'Error.AnnotationForbidden': 'current user cannot update this annotation',
  'Error.AnnotationNotFound': 'annotation does not exist',
  'Error.AssignmentNotActive': 'studio assignment is not active',
  'Error.AssignmentNotFound': 'studio assignment does not exist',
  'Error.AssetNotFound': 'asset does not exist',
  'Error.CannotReviewSelf': 'reviewer and target user must be different',
  'Error.ChapterNotFound': 'chapter or series does not exist',
  'Error.ContractNotExecuted': 'contract gate has not been fulfilled',
  'Error.DownloadForbidden': 'current user cannot download this asset',
  'Error.DuplicateChapterNumber': 'chapter number already exists in this series',
  'Error.DuplicateActiveCollaboration': 'an active collaboration or pending invite already exists for this pair',
  'Error.EmailAlreadyExists': 'email is already used',
  'Error.EmailAlreadyVerified': 'email is already verified',
  'Error.EmailNotFound': 'email does not exist',
  'Error.EmailNotVerified': 'email is not verified',
  'Error.FileTooLarge': 'file exceeds upload size limit',
  'Error.GoogleAccountMismatch': 'google account does not match existing account',
  'Error.GoogleAccountNotRegistered': 'google account is not registered',
  'Error.GoogleEmailNotVerified': 'google email is not verified',
  'Error.InvalidGoogleToken': 'google token is invalid',
  'Error.InvalidManuscriptTransition': 'manuscript state transition is not allowed',
  'Error.InvalidNameState': 'name state does not allow this action',
  'Error.InvalidOTP': 'OTP code is invalid',
  'Error.InvalidPageTransition': 'page state transition is not allowed',
  'Error.InvalidHirePeriod': 'hire period is invalid (start must be before end, end in the future)',
  'Error.InvalidPassword': 'password is invalid',
  'Error.InvalidProposalState': 'proposal state does not allow this action',
  'Error.InvalidSeriesTransition': 'series state transition is not allowed',
  'Error.NameNotApproved': 'name must be approved before this action',
  'Error.InviteNotFound': 'collaboration invite does not exist',
  'Error.InviteNotPending': 'invite is not in PENDING state',
  'Error.NotInviteOwner': 'current user is not the invite owner',
  'Error.NotInvitee': 'current user is not the invitee',
  'Error.NameNotFound': 'name does not exist',
  'Error.NameNotInSeries': 'name does not belong to this series',
  'Error.NotAssignedEditor': 'current editor is not assigned to this series',
  'Error.NotificationNotFound': 'notification does not exist or does not belong to the current user',
  'Error.NotSeriesEditor': 'current user is not the assigned series editor',
  'Error.NotSeriesOwner': 'current user is not the series owner',
  'Error.NotAssignmentOwner': 'current user is not the owner of this assignment',
  'Error.OTPExpired': 'OTP code has expired',
  'Error.OTPLocked': 'OTP attempts are locked',
  'Error.OtpRateLimited': 'too many OTP requests',
  'Error.PageNotFound': 'page does not exist',
  'Error.AssistantNotFound': 'assistant does not exist or is not active',
  'Error.TargetNotAssistant': 'target user is not an assistant',
  'Error.PagesNotAllCompleted': 'all pages must be completed first',
  'Error.ParentSeriesNotFound': 'parent series does not exist',
  'Error.ProfileNotFound': 'profile does not exist',
  'Error.ProposalNotDeletable': 'proposal cannot be deleted in current state',
  'Error.ProposalNotEditable': 'proposal cannot be edited in current state',
  'Error.RefreshTokenAlreadyUsed': 'refresh token has already been used',
  'Error.ReviewAlreadyStarted': 'review has already started',
  'Error.ReviewRequiresEndedAssignment': 'review requires an ended studio assignment between the pair',
  'Error.SeriesAccessDenied': 'current user cannot access this series',
  'Error.SeriesAlreadyClaimed': 'series has already been claimed',
  'Error.SeriesNotFound': 'series does not exist',
  'Error.SeriesNotReadyToPitch': 'series is not ready to pitch',
  'Error.UnauthorizedAccess': 'authentication token is missing or invalid',
  'Error.UnsupportedFileType': 'file type is not allowed',
  'Error.UserNotFound': 'user does not exist',
  'Error.RegionNotFound': 'region not found or invalid id',
  'Error.RegionHasTasks': 'region still has tasks; cannot delete',
  'Error.TaskNotFound': 'task not found or invalid id',
  'Error.NotTaskAssignee': 'caller is not the assigned assistant of this task',
  'Error.AssistantNotHired': 'assistant has no ACTIVE studio assignment within hire period (BR-ASSIST-01)',
  'Error.TaskNotReassignable': 'task must be ON_HOLD to reassign',
  'Error.InvalidTaskTransition': 'invalid task status transition'
}
