//error-docs.ts dùng cho Swagger error description.
export const ERROR_HINTS: Record<string, string> = {
  'Error.PublicSeriesNotFound':
    'series does not exist, id is malformed, or the series is outside the post-serialization public status set',
  'Error.PublicChapterNotFound':
    'chapter does not exist, id is malformed, chapter is not PUBLISHED, or its series is not public',
  'Error.PublicRateLimited': 'IP exceeded the public route quota; retry after the response retryAfter duration',
  'Error.CaptchaRejected':
    'reCAPTCHA verification failed or score is below VotingConfig.captchaThreshold when RECAPTCHA_SECRET is enabled',
  'Error.RevisionRequestNotFound': 'revision request does not exist (or malformed id)',
  'Error.NotRevisionRecipient': 'only the person asked to make the fix (recipientId) can resolve this revision round',
  'Error.AccountBanned': 'account is banned or blocked',
  'Error.AiEnqueueFailed': 'could not enqueue AI job (queue unavailable); use manual regions',
  'Error.AiJobNotApplicable': 'AI job is not in SUCCEEDED state or has no proposed regions',
  'Error.AiJobNotFound': 'AI job does not exist or does not belong to the current user',
  'Error.AiNotEnabled': 'AI service is not configured (AI_SERVICE_URL empty); use manual regions',
  'Error.AnnotationForbidden': 'current user cannot update this annotation',
  'Error.AnnotationNotFound': 'annotation does not exist',
  'Error.AnnotationTargetNotFound': 'targetId does not exist (or malformed id) for the chosen targetType',
  'Error.AssignmentNotActive': 'studio assignment is not active',
  'Error.AssignmentNotFound': 'studio assignment does not exist',
  'Error.AssetNotFound': 'asset does not exist',
  'Error.CannotReviewSelf': 'reviewer and target user must be different',
  'Error.CannotModifyAdminUser': 'super admin users cannot be modified by admin moderation routes',
  'Error.ChapterNotFound':
    'chapter does not exist (or id is not a valid ObjectId) — used by POST /chapters/:id/names (Spec 10)',
  'Error.ChapterAccessDenied': 'caller is outside the chapter scope (owner mangaka / assigned editor / board / admin)',
  'Error.ChapterNotHoldable': 'manuscript must be IN_PRODUCTION..READY_FOR_PRINT to hold',
  'Error.ChapterAlreadyOnHold': 'chapter is already on hold',
  'Error.ChapterNotOnHold': 'chapter is not on hold; nothing to resume',
  'Error.SeriesNotSerialized':
    'Series phải ở SERIALIZED (hoặc CANCELLING/COMPLETING cho chương kết thúc) mới tạo được chapter',
  'Error.EndingAllowanceExceeded': 'Series CANCELLING đã tạo đủ số chương kết thúc Board cấp (endingChapterAllowance)',
  'Error.SurveyPeriodNotFinalized':
    'Kỳ bình chọn chưa REFLECTED (chưa finalize) — kết quả public chỉ xem được sau khi chốt',
  'Error.ContractNotExecuted': 'series has no FULLY_EXECUTED contract; cannot publish (BR-CONTRACT-05)',
  'Error.InvalidContractTransition': 'contract status transition not allowed by CONTRACT_TRANSITIONS (Flow 6)',
  'Error.InvalidSerializationDecision':
    'boardDecisionId must be an APPROVED SERIALIZATION decision for the same series',
  'Error.ContractMangakaMismatch': 'mangakaId must be the current owner of the series',
  'Error.OpenContractExists': 'the series or Board Decision already has a contract that is still active',
  'Error.ContractNotSignableYet': 'contract must reach BOARD_APPROVED before it can be signed (B-CON-02)',
  'Error.ContractNotExecutedForPdf':
    'PDF can only be exported once the contract is FULLY_EXECUTED or terminal (Spec 24)',
  'Error.NotCoOwner': 'only the series co-owner (PARTIAL_TRANSFER) can approve/reject this chapter',
  'Error.CoOwnerApprovalNotPending': 'co-owner approval is not PENDING; already decided or escalated',
  'Error.CoOwnerApprovalNotFound': 'no co-owner approval record exists for this chapter',
  'Error.InvalidTransferState': 'transfer request is not in the required state for this action (B-TRF-03)',
  'Error.ValuationRequired': 'a positive valuationAmount is required for Full Buyout re-valuation (B-TRF-02)',
  'Error.RevenueNotApplicable': 'contract must be REVENUE_SHARE and FULLY_EXECUTED to report revenue',
  'Error.DeadlineRequestAccessDenied': 'current user cannot access or mutate this deadline request',
  'Error.DeadlineRequestNotAllowed': 'deadline action is not allowed for the current chapter or request state',
  'Error.DeadlineRequestNotFound': 'deadline request, chapter, or schedule does not exist',
  'Error.DownloadForbidden': 'current user cannot download this asset',
  'Error.DuplicateChapterNumber': 'chapter number already exists in this series',
  'Error.DuplicatePageNumber': 'page number already exists in this chapter',
  'Error.PageHasApprovedTasks': 'page has approved task(s); cannot delete',
  'Error.PagesNotReadyForPublish': 'chapter still has non-COMPLETED (unreviewed) page(s); cannot publish',
  'Error.DuplicateChapterName': 'chapter-Name already exists for this chapter number (kind=CHAPTER)',
  'Error.DuplicateActiveCollaboration': 'an active collaboration or pending invite already exists for this pair',
  'Error.EmailAlreadyExists': 'email is already used',
  'Error.EmailAlreadyVerified': 'email is already verified',
  'Error.EmailNotFound': 'email does not exist',
  'Error.EmailNotVerified': 'email is not verified',
  'Error.FileTooLarge': 'file exceeds upload size limit',
  'Error.FranchiseConsentRequired': 'derivative needs original mangaka consent (APPROVED) before submit',
  'Error.GoogleAccountMismatch': 'google account does not match existing account',
  'Error.GoogleAccountNotRegistered': 'google account is not registered',
  'Error.GoogleEmailNotVerified': 'google email is not verified',
  'Error.InvalidGoogleToken': 'google token is invalid',
  'Error.InvalidManuscriptTransition': 'manuscript state transition is not allowed',
  'Error.InvalidNameState': 'name state does not allow this action',
  'Error.InvalidOTP': 'OTP code is invalid',
  'Error.InvalidPageTransition': 'page state transition is not allowed',
  'Error.InvalidDeadlineRequestTransition': 'deadline request state transition is not allowed',
  'Error.DeadlineNotAwaitingBoard':
    'deadline request is not awaiting Board decision (must be BOARD_REVIEW or ESCALATED)',
  'Error.InvalidHirePeriod': 'hire period is invalid (start must be before end, end in the future)',
  'Error.InvalidPassword': 'password is invalid',
  'Error.InvalidProposalState': 'proposal state does not allow this action',
  'Error.InvalidSeriesTransition': 'series state transition is not allowed',
  'Error.NameNotApproved': 'name must be approved before this action',
  'Error.NameNotChapterKind': 'name must be of kind CHAPTER to create a chapter (proposal-Name cannot be used)',
  'Error.InviteNotFound': 'collaboration invite does not exist',
  'Error.InviteNotPending': 'invite is not in PENDING state',
  'Error.NotInviteOwner': 'current user is not the invite owner',
  'Error.NotInvitee': 'current user is not the invitee',
  'Error.NotCounterparty': 'only the counterparty can perform this deadline negotiation action',
  'Error.NameNotFound': 'name does not exist',
  'Error.NameNotInSeries': 'name does not belong to this series',
  'Error.NotAssignedEditor': 'current editor is not assigned to this series',
  'Error.NotificationNotFound': 'notification does not exist or does not belong to the current user',
  'Error.NotSeriesEditor': 'current user is not the assigned series editor',
  'Error.NotOriginalMangaka': 'only the parent series original mangaka can give franchise consent',
  'Error.NotFranchiseConsentTarget': 'series is not a franchise pending consent',
  'Error.NotSeriesOwner': 'current user is not the series owner',
  'Error.NotAssignmentOwner': 'current user is not the owner of this assignment',
  'Error.OpenDeadlineRequestExists': 'an open deadline negotiation already exists for this chapter',
  'Error.OTPExpired': 'OTP code has expired',
  'Error.OTPLocked': 'OTP attempts are locked',
  'Error.OtpRateLimited': 'too many OTP requests',
  'Error.PageNotFound': 'page does not exist',
  'Error.PageHasNoFile': 'page has no uploaded original file to segment',
  'Error.AssistantNotFound': 'assistant does not exist or is not active',
  'Error.TargetNotAssistant': 'target user is not an assistant',
  'Error.NoPagesToSubmit': 'Chapter has no pages; upload at least one page before submitting.',
  'Error.TasksNotAllApproved': 'A non-cancelled task is not APPROVED; approve or cancel every task before submitting.',
  'Error.RevisionNotResolved': 'An open revision request must be resolved before resubmitting.',
  'Error.PageNotEditable': 'The page is with the Editor (COMPLETED) and cannot be edited until revision is requested.',
  'Error.ParentSeriesNotFound': 'parent series does not exist',
  'Error.ProfileNotFound': 'profile does not exist',
  'Error.ProposalNotDeletable': 'proposal cannot be deleted in current state',
  'Error.ProposalNotEditable': 'proposal cannot be edited in current state',
  'Error.RefreshTokenAlreadyUsed': 'refresh token has already been used',
  'Error.ReviewAlreadyStarted': 'review has already started',
  'Error.ReviewRequiresEndedAssignment': 'review requires an ended studio assignment between the pair',
  'Error.SeriesAccessDenied': 'current user cannot access this series',
  'Error.SeriesAlreadyClaimed': 'series has already been claimed',
  'Error.SeriesNotEditable':
    'series đã kết thúc (COMPLETED/CANCELLED/ABANDONED/WITHDRAWN/REJECTED) — không sửa metadata được',
  'Error.SeriesMetadataConflict':
    'series metadata changed concurrently too many times; reload the latest series and retry the patch',
  'Error.SeriesNotFound': 'series does not exist',
  'Error.SeriesNotInEndingState': 'Series không ở trạng thái CANCELLING/COMPLETING nên không thể chốt kết thúc.',
  'Error.SeriesNotReadyToPitch': 'series is not ready to pitch',
  'Error.SegmentJobAlreadyRunning': 'a segmentation job is already queued/running for this page',
  'Error.UnauthorizedAccess': 'authentication token is missing or invalid',
  'Error.UnsupportedFileType': 'file type is not allowed',
  'Error.UserNotFound': 'user does not exist',
  'Error.UserAlreadyDeleted': 'user has already been soft-deleted',
  'Error.UserNotDeleted': 'user is not soft-deleted',
  'Error.RegionNotFound': 'region not found or invalid id',
  'Error.RegionHasApprovedTasks': 'region has approved task(s); cannot delete',
  'Error.TaskNotFound': 'task not found or invalid id',
  'Error.NotTaskAssignee': 'caller is not the assigned assistant of this task',
  'Error.AssistantNotHired': 'assistant has no ACTIVE studio assignment within hire period (BR-ASSIST-01)',
  'Error.TaskNotReassignable':
    'only ASSIGNED/IN_PROGRESS/REVISION_REQUESTED/ON_HOLD tasks can be reassigned; review or cancel submitted tasks first',
  'Error.TaskNotCancellable': 'task is APPROVED/CANCELLED and cannot be cancelled',
  'Error.ChapterOnHold': 'chapter is on hold; resume before production mutations',
  'Error.InvalidTaskTransition': 'invalid task status transition',
  'Error.ContractNotAmendable': 'contract must be FULLY_EXECUTED to create an amendment (BR-CONTRACT-01)',
  'Error.OpenAmendmentExists': 'contract already has a non-terminal amendment (DRAFT/PENDING_SIGNATURES)',
  'Error.AmendmentNotFound': 'amendment id not found under this contract',
  'Error.AmendmentNotEditable': 'amendment can only be edited while DRAFT',
  'Error.AmendmentNotSubmittable': 'amendment can only be submitted while DRAFT',
  'Error.AmendmentNoChanges': 'submit requires at least one changed term + non-empty changedClauses',
  'Error.AmendmentNotPendingSignatures': 'amendment must be PENDING_SIGNATURES to sign/reject',
  'Error.MangakaSignNotRequired': 'FULL_BUYOUT amendment is board-signed only; mangaka signature not required',
  'Error.AmendmentNotVoidable': 'amendment is already terminal (FULLY_EXECUTED/VOIDED)',
  'Error.OwnershipMismatch': 'ownership split must total 100; FULL_BUYOUT stays 100/0',
  // Spec 5 — voting/ranking completion
  'Error.TooManySeriesSelected': 'số series vượt maxSeriesPerVote (VotingConfig); trần cứng 3 theo Requiment §1.15',
  'Error.DuplicateSeriesInVote': 'seriesIds chứa id trùng nhau trong cùng một phiếu (PB-03)',
  'Error.SeriesNotVotable': 'seriesIds chứa id rác/không tồn tại hoặc series không ở trạng thái SERIALIZED (PB-03)',
  'Error.VoteIpLimitExceeded':
    'IP này đã đạt trần số phiếu cho kỳ bình chọn (VotingConfig.ipVotesPerPeriod); chặn trước khi đốt OTP',
  'Error.PublicationVersionNotFound': 'publication version does not exist',
  'Error.InvalidVersionType': 'versionType must be one of ORIGINAL, DIGITAL, FLIPPED',
  'Error.RankingAccessDenied':
    'MANGAKA chỉ xem được series mình sở hữu; EDITOR chỉ xem được series mình phụ trách; BOARD/SUPER_ADMIN xem mọi series',
  // Spec 9 — Part 4: Reprint convention (B2 dedup + Error.* + state-service)
  'Error.ReprintRequestNotFound': 'reprint request does not exist (or id is not a valid ObjectId)',
  'Error.ActiveContractNotFound': 'series has no FULLY_EXECUTED contract; cannot create/manipulate reprint request',
  'Error.OriginalChaptersNotFound': 'no PUBLISHED original chapter exists in the requested chapter range',
  'Error.ReprintChapterNotFound':
    'embedded chapter is not part of this reprint request (or originalChapterId mismatch)',
  'Error.InvalidReprintTransition': 'reprint request state transition is not allowed by REPRINT_REQUEST_TRANSITIONS',
  'Error.ReprintActionNotAllowed': 'mangaka review is only valid for REVENUE_SHARE contracts (Ownership Principle)',
  'Error.ReprintNotWithRevision': 'reviser can only be assigned when revisionMode = WITH_REVISION',
  'Error.ReviserOnlyForFullBuyout': 'reviser can only be assigned when the active contract is FULL_BUYOUT',
  'Error.ReviserMangakaNotFound': 'reviserType=OTHER_MANGAKA requires the target user to have role MANGAKA',
  // Spec 9 — Part 5: Board convention (Error.* + guards + audit + session-state-service + messages)
  'Error.BoardSessionAlreadyExists': 'a board session with this title is already UPCOMING or ACTIVE',
  'Error.BoardSessionNotFound': 'board session does not exist (or id is not a valid ObjectId)',
  'Error.BoardConfigNotFound': 'system has no active BoardConfig row',
  'Error.BoardDecisionNotFound': 'board decision does not exist (or id is not a valid ObjectId)',
  'Error.BoardSessionNotOpen': 'board session is not ACTIVE; voting/config update not allowed',
  'Error.InvalidBoardMembers': 'board member count must be odd to prevent tie votes',
  'Error.InvalidQuorum': 'quorumMin must not exceed total board members',
  'Error.VoterNotAllowed': 'caller is not in session.allowedEditorIds',
  'Error.VoterAlreadyVoted': 'voter has already cast a vote on this decision',
  'Error.BoardConfigLocked': 'cannot update BoardConfig while a session is ACTIVE/UPCOMING',
  'Error.BoardSessionClosedReport': 'cannot submit a series report for a CONCLUDED session',
  'Error.BoardReportNotFound': 'series report does not exist (or id is not a valid ObjectId)',
  'Error.EditorNotInvited': 'caller is not in session.allowedEditorIds for report submission',
  'Error.InvalidBoardSessionTransition': 'board session status transition is not allowed by BOARD_SESSION_TRANSITIONS',
  'Error.NotSessionCreator': 'only the board session creator or a Super Admin can conclude the session',
  'Error.NotContractMangaka':
    'caller is not the mangaka of this contract (approve / request-changes / sign / signing progress)',
  'Error.ContractAccessDenied':
    'contract is outside the caller view scope (mangaka: own, editor: assigned, board: all)',
  'Error.PaymentAccessDenied':
    'payment is outside the caller view scope (receiver: own; editor: assigned contract; mangaka: own contract/series; board/admin: all)',
  'Error.InvalidPhaseTransition': 'session phase only moves forward: PRESENTING -> QA -> VOTING (skipping allowed)',
  'Error.VotingNotOpen': 'castVote requires session.phase = VOTING - the session creator must advance the phase first',
  'Error.DecisionAlreadyFinalized': 'decision already APPROVED/REJECTED/EXPIRED — voting closed',
  'Error.NotSessionParticipant': 'only the session creator, roster members, or a Super Admin can read meeting messages',
  'Error.NotEnoughBoardMembers': 'fewer than 3 active board members exist — cannot form a valid session',
  'Error.RosterSourceRequired': 'provide allowedEditorIds, or seriesId so the roster can be auto-assigned',
  'Error.ChapterNotDraftForName': 'chapter must be in DRAFT status to create a Name',
  'Error.ChapterNameAlreadyExists': 'this chapter already has a Name assigned',
  // Spec 10 — Chapter-first flow (Task 2)
  // Spec 10 — Chapter-first flow (Task 3): Page upload gate
  'Error.ChapterNameNotApproved': 'Name must be APPROVED before uploading pages; create/approve the Name first',
  // Spec 10 — Chapter-first flow (Task 4): Update chapter
  'Error.ChapterNotEditable': 'chapter title cannot be changed after PUBLISHED',
  'Error.ChapterNumberLocked': 'chapterNumber can only be changed while the chapter is in DRAFT status',
  // Spec 10 — Chapter-first flow (Task 5): Delete chapter
  'Error.ChapterNotDeletable': 'chapter can only be deleted while in DRAFT status',
  // Spec 12 — chapter-Name delete (Task 14)
  'Error.NameNotDeletable': 'only a not-yet-approved Name on a DRAFT chapter can be deleted'
}
