export const REPRINT_REQUEST_STATUS = {
  PENDING: 'PENDING',
  MANGAKA_APPROVED: 'MANGAKA_APPROVED',
  BOARD_APPROVED: 'BOARD_APPROVED',
  PROPOSED: 'PROPOSED',
  MANGAKA_REVIEW: 'MANGAKA_REVIEW',
  IN_PRODUCTION: 'IN_PRODUCTION',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
  REJECTED_BY_MANGAKA: 'REJECTED_BY_MANGAKA'
} as const

export const REPRINT_CHAPTER_STATUS = {
  PENDING: 'PENDING',
  IN_REVISION: 'IN_REVISION',
  READY: 'READY',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED'
} as const

export type ReprintRequestStatusType = (typeof REPRINT_REQUEST_STATUS)[keyof typeof REPRINT_REQUEST_STATUS]
export type ReprintChapterStatusType = (typeof REPRINT_CHAPTER_STATUS)[keyof typeof REPRINT_CHAPTER_STATUS]
