export const REPRINT_REQUEST_STATUS = {
  PENDING: 'PENDING',
  MANGAKA_APPROVED: 'MANGAKA_APPROVED',
  BOARD_APPROVED: 'BOARD_APPROVED',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED'
} as const

export const REPRINT_CHAPTER_STATUS = {
  PENDING: 'PENDING',
  IN_REVISION: 'IN_REVISION',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED'
} as const

export type ReprintRequestStatusType = (typeof REPRINT_REQUEST_STATUS)[keyof typeof REPRINT_REQUEST_STATUS]
export type ReprintChapterStatusType = (typeof REPRINT_CHAPTER_STATUS)[keyof typeof REPRINT_CHAPTER_STATUS]
